<?php

namespace AppBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByDateExecution($now){
        return $this->createQueryBuilder("t")
            ->where("YEAR(t.dateOfExecution) = :year")
            ->andWhere("YEAR(t.dateOfExecution) = :year")
            ->andWhere("MONTH(t.dateOfExecution) = :month")
            ->andWhere("DAY(t.dateOfExecution) = :day")
            ->setParameter('year', $now->format("Y"))
            ->setParameter('month', $now->format("m"))
            ->setParameter('day', $now->format("d"))
            ->getQuery()->getResult();
    }

}
